version: '3'

services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hrizolight_db
      POSTGRES_USER: hrizolight
      POSTGRES_PASSWORD: password
